from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setMaximumSize(QtCore.QSize(1000, 900))
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 581, 461))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1050, 900))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.tableWidget = QtWidgets.QTableWidget(self.dashboard)
        self.tableWidget.setGeometry(QtCore.QRect(20, 0, 561, 391))
        self.tableWidget.setMaximumSize(QtCore.QSize(1000, 900))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.add_product_btn = QtWidgets.QPushButton(self.dashboard)
        self.add_product_btn.setGeometry(QtCore.QRect(20, 410, 75, 23))
        self.add_product_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_product_btn.setObjectName("add_product_btn")
        self.dlt_product_btn = QtWidgets.QPushButton(self.dashboard)
        self.dlt_product_btn.setGeometry(QtCore.QRect(400, 410, 91, 23))
        self.dlt_product_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dlt_product_btn.setObjectName("dlt_product_btn")
        self.stackedWidget.addWidget(self.dashboard)
        self.customer_shopping_window = QtWidgets.QWidget()
        self.customer_shopping_window.setObjectName("customer_shopping_window")
        self.cart_item_list = QtWidgets.QListWidget(self.customer_shopping_window)
        self.cart_item_list.setGeometry(QtCore.QRect(20, 10, 561, 231))
        self.cart_item_list.setObjectName("cart_item_list")
        self.total_amount = QtWidgets.QLabel(self.customer_shopping_window)
        self.total_amount.setGeometry(QtCore.QRect(30, 250, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.total_amount.setFont(font)
        self.total_amount.setObjectName("total_amount")
        self.procced_topayment_btn = QtWidgets.QPushButton(self.customer_shopping_window)
        self.procced_topayment_btn.setGeometry(QtCore.QRect(290, 260, 171, 31))
        self.procced_topayment_btn.setObjectName("procced_topayment_btn")
        self.stackedWidget.addWidget(self.customer_shopping_window)
        self.payment_recipt_gen_window = QtWidgets.QWidget()
        self.payment_recipt_gen_window.setObjectName("payment_recipt_gen_window")
        self.payment_method = QtWidgets.QComboBox(self.payment_recipt_gen_window)
        self.payment_method.setGeometry(QtCore.QRect(370, 20, 181, 41))
        self.payment_method.setObjectName("payment_method")
        self.payment_method.addItem("")
        self.payment_method.addItem("")
        self.payment_method.addItem("")
        self.recipt = QtWidgets.QTextEdit(self.payment_recipt_gen_window)
        self.recipt.setGeometry(QtCore.QRect(20, 20, 331, 211))
        self.recipt.setObjectName("recipt")
        self.confirm_payment_btn = QtWidgets.QPushButton(self.payment_recipt_gen_window)
        self.confirm_payment_btn.setGeometry(QtCore.QRect(390, 160, 121, 41))
        self.confirm_payment_btn.setObjectName("confirm_payment_btn")
        self.stackedWidget.addWidget(self.payment_recipt_gen_window)
        self.order_history_window = QtWidgets.QWidget()
        self.order_history_window.setObjectName("order_history_window")
        self.order_history = QtWidgets.QTableWidget(self.order_history_window)
        self.order_history.setGeometry(QtCore.QRect(20, 20, 551, 192))
        self.order_history.setObjectName("order_history")
        self.order_history.setColumnCount(0)
        self.order_history.setRowCount(0)
        self.ordr_details = QtWidgets.QLabel(self.order_history_window)
        self.ordr_details.setGeometry(QtCore.QRect(30, 230, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ordr_details.setFont(font)
        self.ordr_details.setObjectName("ordr_details")
        self.view_more_btn = QtWidgets.QPushButton(self.order_history_window)
        self.view_more_btn.setGeometry(QtCore.QRect(320, 260, 111, 31))
        self.view_more_btn.setObjectName("view_more_btn")
        self.stackedWidget.addWidget(self.order_history_window)
        self.gridLayout.addWidget(self.main_body, 1, 2, 1, 1)
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setMaximumSize(QtCore.QSize(180, 900))
        self.sidebar.setStyleSheet("background-color: rgb(42, 45, 56);\n"
"")
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard_btn = QtWidgets.QPushButton(self.sidebar)
        self.dashboard_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_btn.setStyleSheet("border: None;")
        self.dashboard_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icon/icons8-dashboard-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_btn.setIcon(icon)
        self.dashboard_btn.setIconSize(QtCore.QSize(50, 50))
        self.dashboard_btn.setCheckable(False)
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.verticalLayout.addWidget(self.dashboard_btn)
        self.customer_windw_btn = QtWidgets.QPushButton(self.sidebar)
        self.customer_windw_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customer_windw_btn.setStyleSheet("border: None;")
        self.customer_windw_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icon/icons8-add-shopping-cart-90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.customer_windw_btn.setIcon(icon1)
        self.customer_windw_btn.setIconSize(QtCore.QSize(50, 50))
        self.customer_windw_btn.setCheckable(False)
        self.customer_windw_btn.setObjectName("customer_windw_btn")
        self.verticalLayout.addWidget(self.customer_windw_btn)
        self.payment_windwo_btn = QtWidgets.QPushButton(self.sidebar)
        self.payment_windwo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payment_windwo_btn.setStyleSheet("border: None;")
        self.payment_windwo_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icon/icons8-pay-90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_windwo_btn.setIcon(icon2)
        self.payment_windwo_btn.setIconSize(QtCore.QSize(50, 50))
        self.payment_windwo_btn.setObjectName("payment_windwo_btn")
        self.verticalLayout.addWidget(self.payment_windwo_btn)
        self.cart_checkout_windwo_btn = QtWidgets.QPushButton(self.sidebar)
        self.cart_checkout_windwo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cart_checkout_windwo_btn.setStyleSheet("border: None;")
        self.cart_checkout_windwo_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Icon/icons8-cheque-90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cart_checkout_windwo_btn.setIcon(icon3)
        self.cart_checkout_windwo_btn.setIconSize(QtCore.QSize(50, 50))
        self.cart_checkout_windwo_btn.setObjectName("cart_checkout_windwo_btn")
        self.verticalLayout.addWidget(self.cart_checkout_windwo_btn)
        self.gridLayout.addWidget(self.sidebar, 0, 0, 2, 1)
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMaximumSize(QtCore.QSize(900, 100))
        self.header.setStyleSheet("background-color: rgb(151, 207, 72);")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_text = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.header_text.setFont(font)
        self.header_text.setAlignment(QtCore.Qt.AlignCenter)
        self.header_text.setObjectName("header_text")
        self.horizontalLayout.addWidget(self.header_text)
        self.cart = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cart.setFont(font)
        self.cart.setAlignment(QtCore.Qt.AlignCenter)
        self.cart.setObjectName("cart")
        self.horizontalLayout.addWidget(self.cart)
        self.gridLayout.addWidget(self.header, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock"))
        self.add_product_btn.setText(_translate("MainWindow", "Add Product"))
        self.dlt_product_btn.setText(_translate("MainWindow", "Delete Product"))
        self.total_amount.setText(_translate("MainWindow", "Total Amount: 0"))
        self.procced_topayment_btn.setText(_translate("MainWindow", "Procced To payment"))
        self.payment_method.setItemText(0, _translate("MainWindow", "Cash"))
        self.payment_method.setItemText(1, _translate("MainWindow", "Card"))
        self.payment_method.setItemText(2, _translate("MainWindow", "organs"))
        self.confirm_payment_btn.setText(_translate("MainWindow", "Confirm"))
        self.ordr_details.setText(_translate("MainWindow", "Order Details: "))
        self.view_more_btn.setText(_translate("MainWindow", "View More"))
        self.header_text.setText(_translate("MainWindow", "Grocery Managemnt System"))
        self.cart.setText(_translate("MainWindow", "Cart: 0"))
import icons_qrc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())